name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        go:
          - '1.21'
          - '1.20'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Install dependencies
        run: go mod tidy
      - name: Run tests
        run: go test ./...
  windows:
    strategy:
      matrix:
        go:
          - '1.21'
          - '1.20'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Install dependencies
        run: go mod tidy
      - name: Run tests
        run: go test ./... -short
